---
deployment:
  tasks:
    - export DEPLOYPATH=/home/elel9184/test.elearningcreations.com.au/
    - /bin/rm -rf dist
    - npm install
    - npm run build
    - /bin/find $DEPLOYPATH -mindepth 1 -maxdepth 1 ! -name '.well-known' -exec /bin/rm -rf {} +
    - /bin/cp -R dist/. $DEPLOYPATH
