/*
  # Replace Categories and Seed Mock Courses

  ## Summary
  This migration replaces the 6 existing generic training categories with 10 industry-aligned
  categories based on Australia's most in-demand vocational training sectors, then seeds
  40-50 mock courses (4-5 per category) representative of real qualifications in demand.

  ## Changes

  ### 1. Categories (Replaced)
  Removes the 6 old categories and inserts 10 new ones ranked by national demand:
  1. Aged Care, Disability and Individual Support
  2. Health, Nursing and Allied Health Support
  3. Early Childhood Education and Care
  4. Construction, Building and Civil Trades
  5. Electrotechnology and Clean Energy
  6. Digital, IT and Cyber Security
  7. Training, Assessment and VET
  8. Hospitality, Tourism and Commercial Cookery
  9. Transport, Logistics and Supply Chain
  10. Manufacturing, Defence and Sovereign Capability

  ### 2. Courses (New)
  Inserts 4-5 courses per category, all published, with realistic durations,
  mixed difficulty levels, and AUD pricing.

  ### Security
  Existing RLS policies on both tables remain in place — no changes needed.

  ### Notes
  - Uses DELETE + INSERT pattern (safe — no FK dependents since courses table was empty)
  - All courses marked is_published = true so they appear on the public catalogue
  - A handful marked is_featured = true for the home page
*/

-- Clear existing seed data (courses first due to FK, then categories)
DELETE FROM courses;
DELETE FROM categories;

-- Insert 10 new industry-aligned categories
INSERT INTO categories (id, name, slug, description, icon, sort_order) VALUES
  ('11111111-0001-0000-0000-000000000000', 'Aged Care, Disability and Individual Support', 'aged-care-disability', 'Australia''s highest Fee-Free TAFE enrolment sector. Certificate III in Individual Support is the top enrolled and completed course nationally.', 'Heart', 1),
  ('11111111-0002-0000-0000-000000000000', 'Health, Nursing and Allied Health Support', 'health-nursing-allied', 'Health Care and Social Assistance is Australia''s largest employing industry with the strongest projected growth over the next 5–10 years.', 'Stethoscope', 2),
  ('11111111-0003-0000-0000-000000000000', 'Early Childhood Education and Care', 'early-childhood-education', 'A major Fee-Free TAFE enrolment sector. Certificate III in Early Childhood Education and Care is among the top enrolled and completed courses nationally.', 'Baby', 3),
  ('11111111-0004-0000-0000-000000000000', 'Construction, Building and Civil Trades', 'construction-building', 'A national priority area with persistent shortages in construction trades and technicians reported by Jobs and Skills Australia.', 'HardHat', 4),
  ('11111111-0005-0000-0000-000000000000', 'Electrotechnology and Clean Energy', 'electrotechnology-clean-energy', 'Skill Level 3 trades remain highly shortage-prone. Strong employment outcomes for Electrotechnology completers with growing clean energy demand.', 'Zap', 5),
  ('11111111-0006-0000-0000-000000000000', 'Digital, IT and Cyber Security', 'digital-it-cyber', 'Technology and digital is a national priority sector. Certificate IV in Cyber Security is among the top Fee-Free TAFE priority course activity.', 'Shield', 6),
  ('11111111-0007-0000-0000-000000000000', 'Training, Assessment and VET', 'training-assessment-vet', 'The VET workforce is an explicit national priority. Certificate IV in Training and Assessment is one of the top Fee-Free TAFE enrolled and completed courses.', 'GraduationCap', 7),
  ('11111111-0008-0000-0000-000000000000', 'Hospitality, Tourism and Commercial Cookery', 'hospitality-tourism', 'A national priority sector. Commercial cookery and hospitality qualifications are among the top completed courses in Fee-Free TAFE priority sectors.', 'ChefHat', 8),
  ('11111111-0009-0000-0000-000000000000', 'Transport, Logistics and Supply Chain', 'transport-logistics', 'Jobs and Skills Australia notes shortages and weak vacancy fill rates in machinery operators and drivers, with ongoing demand/supply pressure.', 'Truck', 9),
  ('11111111-0010-0000-0000-000000000000', 'Manufacturing, Defence and Sovereign Capability', 'manufacturing-defence', 'Sovereign capability including manufacturing and defence is a national Fee-Free TAFE priority and named in the National Skills Agreement.', 'Factory', 10);

-- Seed courses: Aged Care, Disability and Individual Support (5 courses)
INSERT INTO courses (title, slug, short_description, description, category_id, price, currency, duration_hours, difficulty_level, is_published, is_featured, sort_order) VALUES
  ('Person-Centred Care Foundations', 'person-centred-care-foundations', 'Learn the principles of person-centred care and how to apply them in aged care and disability support settings.', 'This course covers the core philosophy of person-centred care, including respecting individual dignity, promoting independence, and understanding person-centred active support frameworks used in Australian care environments.', '11111111-0001-0000-0000-000000000000', 79, 'AUD', 3.0, 'beginner', true, true, 1),
  ('Disability Support Essentials', 'disability-support-essentials', 'Build foundational skills for supporting people with disability in community and residential settings.', 'Covers the NDIS framework, disability support worker responsibilities, communication strategies, and rights-based approaches aligned with the NDIS Practice Standards.', '11111111-0001-0000-0000-000000000000', 99, 'AUD', 4.0, 'beginner', true, false, 2),
  ('Manual Handling for Support Workers', 'manual-handling-support-workers', 'Safe manual handling techniques specifically designed for aged care and disability support contexts.', 'Practical training in safe patient and client handling, use of assistive equipment, risk assessment, and legislative requirements under the WHS Act.', '11111111-0001-0000-0000-000000000000', 59, 'AUD', 2.0, 'beginner', true, false, 3),
  ('Dementia Awareness and Responsive Practice', 'dementia-awareness-responsive-practice', 'Understand dementia and develop responsive, evidence-based support strategies for people living with dementia.', 'Explore dementia types, progression, behavioural expressions of unmet need, and contemporary approaches to dementia-inclusive care aligned with the Aged Care Quality Standards.', '11111111-0001-0000-0000-000000000000', 89, 'AUD', 3.5, 'intermediate', true, true, 4),
  ('Managing Challenging Behaviours in Care', 'managing-challenging-behaviours-care', 'Develop skills to understand, prevent and respond to behaviours of concern in care environments.', 'Covers behaviour support principles, positive behaviour support planning, de-escalation strategies, and documentation requirements in accordance with restrictive practices guidelines.', '11111111-0001-0000-0000-000000000000', 109, 'AUD', 4.0, 'intermediate', true, false, 5);

-- Seed courses: Health, Nursing and Allied Health Support (5 courses)
INSERT INTO courses (title, slug, short_description, description, category_id, price, currency, duration_hours, difficulty_level, is_published, is_featured, sort_order) VALUES
  ('Introduction to Nursing Practice', 'introduction-nursing-practice', 'A foundational overview of nursing roles, responsibilities and the Australian healthcare system.', 'Designed for those entering or exploring nursing pathways, this course covers scope of practice, documentation, patient communication, and the structure of Australia''s healthcare system.', '11111111-0002-0000-0000-000000000000', 99, 'AUD', 4.0, 'beginner', true, true, 1),
  ('Infection Control in Healthcare Settings', 'infection-control-healthcare', 'Essential infection prevention and control training for healthcare workers across all clinical settings.', 'Covers standard and transmission-based precautions, hand hygiene, PPE use, environmental cleaning, and outbreak management aligned with NHMRC guidelines.', '11111111-0002-0000-0000-000000000000', 69, 'AUD', 2.5, 'beginner', true, false, 2),
  ('Medication Assistance Fundamentals', 'medication-assistance-fundamentals', 'Understand safe medication assistance practices for support workers and allied health assistants.', 'Covers medication terminology, routes of administration, documentation, recognising adverse reactions, and legal responsibilities for non-registered workers assisting with medications.', '11111111-0002-0000-0000-000000000000', 119, 'AUD', 5.0, 'intermediate', true, false, 3),
  ('Pathology Collection Essentials', 'pathology-collection-essentials', 'Core competencies for pathology collectors including venepuncture and specimen handling.', 'Covers anatomy for collection, venepuncture technique, patient identification, specimen labelling and transport, and workplace health and safety requirements in pathology environments.', '11111111-0002-0000-0000-000000000000', 139, 'AUD', 6.0, 'intermediate', true, false, 4),
  ('Allied Health Assistant Skills', 'allied-health-assistant-skills', 'Build practical skills to support physiotherapists, occupational therapists and other allied health professionals.', 'Covers delegation and supervision frameworks, assisting with exercise programs, equipment preparation, client communication, and documentation requirements for AHAs.', '11111111-0002-0000-0000-000000000000', 109, 'AUD', 4.5, 'beginner', true, false, 5);

-- Seed courses: Early Childhood Education and Care (5 courses)
INSERT INTO courses (title, slug, short_description, description, category_id, price, currency, duration_hours, difficulty_level, is_published, is_featured, sort_order) VALUES
  ('Child Development Foundations', 'child-development-foundations', 'Explore key theories and milestones of child development from birth to 12 years.', 'Covers developmental domains, observation and documentation, play-based learning theories, and how developmental knowledge informs quality early childhood practice.', '11111111-0003-0000-0000-000000000000', 79, 'AUD', 3.0, 'beginner', true, true, 1),
  ('Safe Sleep and Settling Practices', 'safe-sleep-settling-practices', 'Evidence-based safe sleep guidelines and settling strategies for infants and toddlers in ECEC settings.', 'Aligns with Red Nose Australia safe sleep guidelines and ACECQA requirements. Covers safe sleep environments, settling approaches, and risk identification for educators.', '11111111-0003-0000-0000-000000000000', 59, 'AUD', 2.0, 'beginner', true, false, 2),
  ('Inclusive Practice in Early Childhood', 'inclusive-practice-early-childhood', 'Strategies for creating inclusive environments that support children with diverse needs and abilities.', 'Explores the Disability Discrimination Act, reasonable adjustment, working with families, partnering with allied health professionals, and the EYLF inclusion principles.', '11111111-0003-0000-0000-000000000000', 89, 'AUD', 3.5, 'intermediate', true, false, 3),
  ('Behaviour Guidance for ECEC Educators', 'behaviour-guidance-ecec-educators', 'Positive guidance strategies to support children''s social and emotional development in early childhood settings.', 'Covers positive behaviour support, understanding the function of behaviour, preventative strategies, and building nurturing educator-child relationships aligned with the NQS.', '11111111-0003-0000-0000-000000000000', 79, 'AUD', 3.0, 'intermediate', true, false, 4),
  ('Programming and Planning for Learning', 'programming-planning-learning', 'Develop skills in observation, documentation and curriculum planning aligned with the EYLF and NQF.', 'Practical training in learning story writing, portfolio documentation, linking observations to the EYLF outcomes, and cycle of planning for individual and group programming.', '11111111-0003-0000-0000-000000000000', 99, 'AUD', 4.0, 'intermediate', true, false, 5);

-- Seed courses: Construction, Building and Civil Trades (5 courses)
INSERT INTO courses (title, slug, short_description, description, category_id, price, currency, duration_hours, difficulty_level, is_published, is_featured, sort_order) VALUES
  ('Work Health and Safety for Construction', 'whs-construction', 'Essential WHS knowledge for all workers entering construction sites in Australia.', 'Covers WHS legislation, site induction requirements, hazard identification, PPE selection, and reporting obligations relevant to the construction industry.', '11111111-0004-0000-0000-000000000000', 59, 'AUD', 2.0, 'beginner', true, false, 1),
  ('Working at Heights Awareness', 'working-at-heights-awareness', 'Understand the risks and controls for work at height in construction and civil environments.', 'Covers the hierarchy of controls for falls, types of fall protection systems, harness inspection basics, and legislative requirements under the WHS Regulations.', '11111111-0004-0000-0000-000000000000', 79, 'AUD', 3.0, 'beginner', true, false, 2),
  ('Asbestos Awareness for Construction Workers', 'asbestos-awareness-construction', 'Identify and safely manage asbestos-containing materials in construction and renovation work.', 'Covers the health risks of asbestos, how to identify ACMs in buildings, stop-work obligations, reporting requirements, and legal duties under the WHS Regulations.', '11111111-0004-0000-0000-000000000000', 69, 'AUD', 2.5, 'beginner', true, false, 3),
  ('Reading and Interpreting Construction Plans', 'reading-construction-plans', 'Build confidence reading architectural drawings, engineering plans and specifications on construction sites.', 'Covers drawing conventions, scales, symbols, cross-sections, site plans, and how to extract key information from construction documentation.', '11111111-0004-0000-0000-000000000000', 109, 'AUD', 5.0, 'intermediate', true, false, 4),
  ('Traffic Management Fundamentals', 'traffic-management-fundamentals', 'Core competencies for traffic controllers and road workers managing traffic around worksites.', 'Covers traffic control devices, worksite communication, personal safety, legal requirements, and practical skills aligned with the Traffic Controller training package.', '11111111-0004-0000-0000-000000000000', 89, 'AUD', 3.5, 'beginner', true, false, 5);

-- Seed courses: Electrotechnology and Clean Energy (4 courses)
INSERT INTO courses (title, slug, short_description, description, category_id, price, currency, duration_hours, difficulty_level, is_published, is_featured, sort_order) VALUES
  ('Electrical Safety Essentials', 'electrical-safety-essentials', 'Foundational electrical safety awareness for workers in and around electrical environments.', 'Covers electrical hazards, safe work distances, LOTO/isolation procedures, electrical burns and shock first aid, and when to engage a licensed electrician.', '11111111-0005-0000-0000-000000000000', 69, 'AUD', 2.5, 'beginner', true, false, 1),
  ('Solar PV System Fundamentals', 'solar-pv-system-fundamentals', 'Introduction to solar photovoltaic systems, components, safety and the Australian clean energy landscape.', 'Covers solar PV technology, system components, roof safety, DC and AC circuit basics, metering, and an overview of the CEC accreditation pathway for solar installers.', '11111111-0005-0000-0000-000000000000', 119, 'AUD', 5.0, 'beginner', true, true, 2),
  ('Battery Storage and Clean Energy Systems', 'battery-storage-clean-energy', 'Understand battery storage technologies and their integration with solar and grid systems.', 'Explores lithium-ion and flow battery technologies, battery management systems, safety requirements, grid connection rules, and the growing role of storage in Australia''s energy transition.', '11111111-0005-0000-0000-000000000000', 129, 'AUD', 5.5, 'intermediate', true, false, 3),
  ('EV Charging Infrastructure Basics', 'ev-charging-infrastructure-basics', 'Introduction to electric vehicle charging systems, installation considerations and the Australian EV market.', 'Covers EV charging levels (AC/DC), load management, grid impact, installation standards, and workplace and residential charging deployment.', '11111111-0005-0000-0000-000000000000', 99, 'AUD', 4.0, 'intermediate', true, false, 4);

-- Seed courses: Digital, IT and Cyber Security (5 courses)
INSERT INTO courses (title, slug, short_description, description, category_id, price, currency, duration_hours, difficulty_level, is_published, is_featured, sort_order) VALUES
  ('Cyber Security Awareness for Business', 'cyber-security-awareness-business', 'Protect your organisation from common cyber threats with practical, easy-to-apply security knowledge.', 'Covers phishing, social engineering, password hygiene, safe browsing, data classification, and what to do when a cyber incident occurs. Aligned with the ASD Essential Eight.', '11111111-0006-0000-0000-000000000000', 59, 'AUD', 2.0, 'beginner', true, true, 1),
  ('Microsoft 365 Productivity Essentials', 'microsoft-365-productivity-essentials', 'Get more out of Microsoft 365 with practical skills in Teams, SharePoint, OneDrive and Outlook.', 'Hands-on training in the Microsoft 365 suite for everyday business users. Covers collaboration tools, file management, meeting best practices, and productivity tips.', '11111111-0006-0000-0000-000000000000', 79, 'AUD', 3.0, 'beginner', true, false, 2),
  ('Introduction to Cloud Computing', 'introduction-cloud-computing', 'Understand cloud fundamentals, service models and how cloud technology is reshaping Australian workplaces.', 'Covers IaaS, PaaS and SaaS models, major cloud providers, cloud security basics, compliance considerations, and the business case for cloud migration.', '11111111-0006-0000-0000-000000000000', 99, 'AUD', 4.0, 'beginner', true, false, 3),
  ('Data Privacy and the Australian Privacy Act', 'data-privacy-australian-privacy-act', 'Understand your obligations under the Australian Privacy Act and the Notifiable Data Breaches scheme.', 'Covers the 13 Australian Privacy Principles, employee and customer data rights, privacy by design, data breach notification obligations, and building a privacy-aware workplace culture.', '11111111-0006-0000-0000-000000000000', 89, 'AUD', 3.5, 'intermediate', true, false, 4),
  ('IT Helpdesk and Support Fundamentals', 'it-helpdesk-support-fundamentals', 'Build the core technical and interpersonal skills needed to work effectively in an IT support role.', 'Covers hardware and software troubleshooting methodologies, ticketing systems, remote support tools, service desk communication, and escalation procedures.', '11111111-0006-0000-0000-000000000000', 109, 'AUD', 4.5, 'intermediate', true, false, 5);

-- Seed courses: Training, Assessment and VET (5 courses)
INSERT INTO courses (title, slug, short_description, description, category_id, price, currency, duration_hours, difficulty_level, is_published, is_featured, sort_order) VALUES
  ('Facilitation Skills for Trainers', 'facilitation-skills-trainers', 'Develop engaging facilitation techniques to deliver effective training in face-to-face and blended environments.', 'Covers adult learning principles, training room management, questioning techniques, managing group dynamics, and adjusting delivery to meet diverse learner needs.', '11111111-0007-0000-0000-000000000000', 99, 'AUD', 4.0, 'beginner', true, false, 1),
  ('Assessment Design and Validation', 'assessment-design-validation', 'Design and validate assessment tools that meet the Standards for RTOs 2015.', 'Covers assessment principles (validity, reliability, flexibility, fairness), assessment tool construction, evidence requirements, RPL assessment, and the validation cycle.', '11111111-0007-0000-0000-000000000000', 119, 'AUD', 5.0, 'intermediate', true, false, 2),
  ('Delivering Online and Blended Learning', 'delivering-online-blended-learning', 'Practical strategies for designing and facilitating effective online and blended training programs.', 'Explores LMS platforms, synchronous and asynchronous delivery, learner engagement in digital environments, accessibility, and evaluating online learning outcomes.', '11111111-0007-0000-0000-000000000000', 109, 'AUD', 4.5, 'intermediate', true, false, 3),
  ('Contextualising Training Resources', 'contextualising-training-resources', 'Learn how to adapt and contextualise nationally recognised training resources for your industry and learners.', 'Covers the rules and boundaries of contextualisation within Training Packages, industry mapping, reading and interpreting Units of Competency, and learner resource adaptation.', '11111111-0007-0000-0000-000000000000', 89, 'AUD', 3.5, 'intermediate', true, false, 4),
  ('RTO Compliance and the AQF', 'rto-compliance-aqf', 'Build your knowledge of RTO regulatory obligations, the Standards for RTOs 2015, and the Australian Qualifications Framework.', 'Covers the role of ASQA, the Standards for RTOs, AQF qualification types, scope of registration, continuous improvement obligations, and common compliance pitfalls.', '11111111-0007-0000-0000-000000000000', 129, 'AUD', 5.5, 'advanced', true, false, 5);

-- Seed courses: Hospitality, Tourism and Commercial Cookery (5 courses)
INSERT INTO courses (title, slug, short_description, description, category_id, price, currency, duration_hours, difficulty_level, is_published, is_featured, sort_order) VALUES
  ('Food Safety Supervisor Essentials', 'food-safety-supervisor-essentials', 'Meet your legal obligations as a Food Safety Supervisor under the Australia New Zealand Food Standards Code.', 'Covers food safety hazards, temperature control, cross-contamination prevention, cleaning and sanitising, food handler training obligations, and record keeping requirements.', '11111111-0008-0000-0000-000000000000', 79, 'AUD', 3.0, 'beginner', true, true, 1),
  ('Responsible Service of Alcohol', 'responsible-service-alcohol', 'Understand your legal obligations and practical strategies for the responsible service of alcohol.', 'Covers liquor licensing legislation, identifying intoxication, refusing service, managing difficult situations, and the legal liability of licensees, managers and servers.', '11111111-0008-0000-0000-000000000000', 59, 'AUD', 2.0, 'beginner', true, false, 2),
  ('Barista and Coffee Essentials', 'barista-coffee-essentials', 'Master the fundamentals of espresso extraction, milk texturing, and café customer service.', 'Covers coffee origins and varieties, espresso machine operation, grind adjustment, milk steaming and latte art basics, and maintaining equipment hygiene standards.', '11111111-0008-0000-0000-000000000000', 89, 'AUD', 3.5, 'beginner', true, false, 3),
  ('Front of House Service Skills', 'front-of-house-service-skills', 'Deliver exceptional guest experiences with professional front-of-house service techniques.', 'Covers service sequences, menu knowledge, table management, handling complaints, upselling techniques, and working effectively as part of a hospitality team.', '11111111-0008-0000-0000-000000000000', 79, 'AUD', 3.0, 'beginner', true, false, 4),
  ('Commercial Kitchen Safety and Hygiene', 'commercial-kitchen-safety-hygiene', 'Essential safety and food hygiene practices for all workers in a commercial kitchen environment.', 'Covers kitchen hazard identification, safe knife handling, burns and spill prevention, PPE requirements, allergen awareness, and maintaining a clean food preparation environment.', '11111111-0008-0000-0000-000000000000', 69, 'AUD', 2.5, 'beginner', true, false, 5);

-- Seed courses: Transport, Logistics and Supply Chain (5 courses)
INSERT INTO courses (title, slug, short_description, description, category_id, price, currency, duration_hours, difficulty_level, is_published, is_featured, sort_order) VALUES
  ('Chain of Responsibility Essentials', 'chain-of-responsibility-essentials', 'Understand your obligations under the Heavy Vehicle National Law Chain of Responsibility provisions.', 'Covers the expanded CoR framework, the primary duty of care, due diligence requirements for executives and schedulers, and building a safety management system for transport operations.', '11111111-0009-0000-0000-000000000000', 79, 'AUD', 3.0, 'beginner', true, false, 1),
  ('Forklift Safety Awareness', 'forklift-safety-awareness', 'Understand forklift hazards, safe operating zones, and pre-operational checks for workers in logistics environments.', 'Designed for non-operators working in environments where forklifts operate. Covers blind spots, exclusion zones, pedestrian safety, and communication with operators.', '11111111-0009-0000-0000-000000000000', 59, 'AUD', 2.0, 'beginner', true, false, 2),
  ('Dangerous Goods Handling and Transport', 'dangerous-goods-handling-transport', 'Safe handling, storage and transport of dangerous goods in accordance with Australian regulations.', 'Covers the ADG Code, dangerous goods classification, placarding, documentation, emergency response information, and duties of consignors, packers and drivers.', '11111111-0009-0000-0000-000000000000', 99, 'AUD', 4.0, 'intermediate', true, false, 3),
  ('Warehouse Induction and Safety', 'warehouse-induction-safety', 'Essential induction knowledge for all new workers entering a warehouse or distribution centre.', 'Covers site layout and emergency procedures, manual handling, racking safety, housekeeping standards, PPE requirements, and reporting hazards and incidents.', '11111111-0009-0000-0000-000000000000', 59, 'AUD', 2.0, 'beginner', true, false, 4),
  ('Load Restraint Fundamentals', 'load-restraint-fundamentals', 'Understand the principles and techniques for safely restraining loads on road transport vehicles.', 'Covers the Load Restraint Guide requirements, friction, blocking and lashing methods, tie-down ratings, vehicle inspection, and driver responsibilities under the HVNL.', '11111111-0009-0000-0000-000000000000', 89, 'AUD', 3.5, 'intermediate', true, false, 5);

-- Seed courses: Manufacturing, Defence and Sovereign Capability (4 courses)
INSERT INTO courses (title, slug, short_description, description, category_id, price, currency, duration_hours, difficulty_level, is_published, is_featured, sort_order) VALUES
  ('Quality Management in Manufacturing', 'quality-management-manufacturing', 'Apply quality management principles and tools to improve processes and outcomes in manufacturing environments.', 'Covers ISO 9001 fundamentals, quality control vs quality assurance, inspection methods, non-conformance management, root cause analysis, and continuous improvement culture.', '11111111-0010-0000-0000-000000000000', 119, 'AUD', 5.0, 'intermediate', true, false, 1),
  ('Lean and 5S Workplace Principles', 'lean-5s-workplace-principles', 'Reduce waste and improve workplace organisation using Lean manufacturing and 5S methodology.', 'Covers the 8 wastes of Lean, 5S implementation (Sort, Set, Shine, Standardise, Sustain), visual management, standard work, and building a continuous improvement mindset.', '11111111-0010-0000-0000-000000000000', 99, 'AUD', 4.0, 'beginner', true, false, 2),
  ('Safe Use of Machinery and Guarding', 'safe-use-machinery-guarding', 'Understand machinery hazards, guarding requirements and safe operating procedures in manufacturing settings.', 'Covers machinery risk assessment, types of guarding, isolation and lockout/tagout, safe operating procedures, and legislative requirements under the WHS Regulations and AS 4024.', '11111111-0010-0000-0000-000000000000', 79, 'AUD', 3.0, 'beginner', true, false, 3),
  ('Sovereign Supply Chain Awareness', 'sovereign-supply-chain-awareness', 'Understand Australia''s sovereign capability agenda and what it means for local manufacturers and defence suppliers.', 'Covers the National Defence Strategy, the Sovereign Industrial Capability Priority areas, supply chain resilience principles, and opportunities for Australian manufacturers in defence and critical industries.', '11111111-0010-0000-0000-000000000000', 89, 'AUD', 3.5, 'intermediate', true, false, 4);
